### ISSUE TITLE
Remove unnecessary code

### ISSUE THREAD

**Issue by itsfolf** [SeanOMik/TamableFoxes#61]
All the ASM code you pulled from my fork isn't necessary for the field reflection without JVM arguments, those are a few experiments I'm doing with dynamically generating and editing fox classes (which is totally broken atm). All that is needed are the updates to FieldHelper.

**Comment by itsfolf** [comment]
I'm also not totally sure if the new method works on <16 Java versions, you might need to add a check for that

**Comment by SeanOMik** [comment]
> All the ASM code you pulled from my fork isn't necessary for the field reflection without JVM arguments, those are a few experiments I'm doing with dynamically generating and editing fox classes (which is totally broken atm). All that is needed are the updates to FieldHelper.

I think I tried to take just the code for FieldHelper but it didn't work. I also kind of rushed the code changes since I've been busy lately and I just wanted to get something released, but I'll mess with it when I get some more time. So I'll keep this issue open until I mess with it more

> I'm also not totally sure if the new method works on <16 Java versions, you might need to add a check for that

I did test it on older Java versions (Java 8) before releasing and it worked fine.

**Comment by SeanOMik** [comment]
So idk how I got errors when I took just the FieldHelper code, but it works fine now lol. I'll wait to make a new release unless the old stuff I had in there starts causing issues for some users.

Anyway, thanks again for finding a fix for the program arguments!
